Rhel9 baseline container
warewulf/warewulf-node-images pull request #34
Opened 2023-11-29 09:01 UTC by sjjamsa

We just started using this container as our base image. Perhaps it could be shown e.g. as an example for others.

2023-11-30 06:32 UTC, sjjamsa commented
So the things I copied from John Hanks were to:

 -  use the normal redhat UBI container [registry.access.redhat.com/ubi9/ubi](http://registry.access.redhat.com/ubi9/ubi)
 -  Unmasking some systemd services
 -  There is the commented out subscription copying.

I think other changes compared to Rocky-9 are more or less accidental, and I could align the files more, if so wished.

2024-05-08 11:58 UTC, mslacken approved these changes

2024-05-08 11:59 UTC, mslacken approved these changes

2024-05-08 14:55 UTC, anderbubble requested changes
Thanks for submitting this, @sjjamsa!

Can you move this to the `examples/` directory, and add a README?

I also recommend providing an example `podman` command that uses volume mounts to bring in the necessary subscription files, rather than COPYing them into the container.

2024-11-07 20:32 UTC, anderbubble commented
Closing in favor of #60, since I can't push into AaltoSciComp:rhel9 to make requested changes.

2024-11-07 20:32 UTC, closed without merging